function x = gauss_seidel_solver(A, b)
    [B, c] = gauss_seidel(A, b);
    x = solve_iterative( ...
       B, c, ...
       ones(length(b), 1), 1e-5, ...
       @(x1, x2) norm(x1 - x2), ...
       200 ...
   );
end